name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: |
        dotnet restore src/OpenCVCameraTracking.Core/OpenCVCameraTracking.Core.csproj
        dotnet restore src/OpenCVCameraTracking/OpenCVCameraTracking.csproj

    - name: Build
      run: |
        dotnet build src/OpenCVCameraTracking.Core/OpenCVCameraTracking.Core.csproj -c Release --no-restore
        dotnet build src/OpenCVCameraTracking/OpenCVCameraTracking.csproj -c Release --no-restore

    - name: Upload build artifact
      uses: actions/upload-artifact@v5
      with:
        name: OpenCVCameraTracking
        path: |
          src/OpenCVCameraTracking/bin/Release/
          src/OpenCVCameraTracking.Core/bin/Release/
        retention-days: 7
